language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
  - sudo apt-get -y install libgtk-3-dev libav-tools

script:
  - make -j$(nproc)
  - install -Dm 0755 /usr/bin/avprobe appdir/usr/bin/avprobe
  - install -Dm 0755 /usr/bin/avconv appdir/usr/bin/avconv
  - install -Dm 0644 data/com.github.JannikHv.Gydl.desktop appdir/usr/share/applications/gydl.desktop # FIXME
  - install -Dm 0644 data/com.github.JannikHv.Gydl.appdata.xml appdir/usr/share/metainfo/com.github.JannikHv.Gydl.appdata.xml # FIXME
  - install -Dm 0644 data/gydl.svg appdir/usr/share/icons/hicolor/scalable/apps/gydl.svg # FIXME
  - install -Dm 0644 LICENSE appdir/usr/share/licenses/gydl/LICENSE # FIXME
  - install -Dm 0755 gydl appdir/usr/bin/gydl # FIXME
  - wget -c "https://yt-dl.org/downloads/latest/youtube-dl" -O appdir/usr/bin/youtube-dl
  - |
    cat > appdir/AppRun <<\EOF
    #!/bin/bash
    HERE=$(dirname $(readlink -f "${0}"))
    export PATH=$HERE:$HERE/usr/bin:$PATH
    exec "${HERE}/usr/bin/gydl" "$@"
    EOF
  - chmod a+rx appdir/usr/bin/youtube-dl appdir/AppRun
  - find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - |
    ARCH=x86_64 ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage \
    -exclude-libs=libgtk-3.so.0,libgdk-3.so.0 -executable=appdir/usr/bin/avprobe -executable=appdir/usr/bin/avconv

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Gydl*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
